### ISSUE TITLE
Counter-intuitive result in tutorial

### ISSUE THREAD

**Issue by vakker** [rte-france/Grid2Op#237]
## Environment
 - Grid2op version: `d516e1c`
 - System: `Ubuntu20.04`

## Bug description
I was going though the tutorial (1_Power_Grid_101_notebook) and I wanted to have a more intuitive understanding of how the grid reacts to the power line disconnect. E.g. (see figure below) when an outflow line from `bus 0` is disconnected, then how can an inflow line be overloaded? I thought the non-linear response could be the reason, but it's still very counter-intuitive. 

Then I looked more into it and the two lines that go into `bus 4` go from 59.57% and 59.80% to 78.44% and 78.99% (respectively). However, the load connected to `bus 4` stays the same (-7.70 MW), so how can the load increase on both lines flowing INTO `bus 4`? That seems to contradict the conservation of energy, however the `p_ex` values add up to 7.70 MW (3.8626506 + 3.8373492 and then 3.8952487 + 3.8047512).

Also, there's less power flowing INTO `bus 3` due to the disconnect and also because the 2 parallel lines show lower load, however there's more load on the line flowing OUT of the bus compared to the initial values.

Does this look correct? Am I missing something here?

![state_0](https://user-images.githubusercontent.com/3268882/123712910-33609500-d86b-11eb-9f51-e0fe12945474.png)
![state_1](https://user-images.githubusercontent.com/3268882/123712912-33f92b80-d86b-11eb-93c7-fd3c45777a80.png)

## How to reproduce
Run the tutorial notebook.

**Comment by BDonnot** [comment]
Hello,

You are totally right, power system are really complex objects. And most of the time, they behave in a counter intuitive manner.
Current flow does not behave like fluid flowing in pipes. This might be what you call "counter intuitive" here. 

> Does this look correct? 

Yes it is, we made lots of check to make sure the "power grid equations" were correctly implemented in lightsim2grid (the grid2op "backend" / "powergrid solver" used for the competition).

If you did not installed "lightsim2grid" you are by default using "pandapower" which is a python library to compute powerflows and that is heavily tested as well.

> Am I missing something here?

It's not easy to see what is happening if you look at the "relative flow" here.

It is, I think, clearer if you look at both its components: the active (in MW, accessible for example `obs.p_or` and `obs.p_ex` in grid2op) and the reactive (in MVAr, accessible with `obs.q_or` and `obs.q_ex`)

So i would say you are "missing" on the "reactive part" of the flow there.

> how can an inflow line be overloaded?

Long story short (and I insist, this is a "story" to exaplain something in a consistent manner):
- you need to get some power from gen 1 to load 0 (on substation 0) and load 2 (on substation 4)
- before line *0 -- 3* disconnect, you can provide enough power (in W)  to load 2 with the "routes" *1 --> 2 --> 0 --> 3 --> 4*  and *1 --> 2 --> 0 --> 4*
- when you disconnect line *0 -- 3* you cut off the first route, so you put more pressure to the "route" *1 --> 2 --> 0 --> 4* and it happens to overflow one of its "segment" (in this case  *0 -- 2*) and increase the flow on the "segment" *0 -- 4* [this is the "easy" part]

> so how can the load increase on both lines flowing INTO bus 4?

Now, i'll try to explain the "why the flow on *3 -- 4* increases too. It will be not too disappointing I hope. If it is, let me know and i'll try to clarify what is still unclear.

Well, for that, i need to get into the gory details of reactive. What is reactive power ? Well... It can be seen as lots of different "aspect", but for me it's a part that is needed by the model to make things work. Without it, you cannot easily describe how a powergrid behaves. So it appears in the equations and you cannot get rid of it. You can consult some documentation online on reactive power I believe, or ask me if you need more than "it's here and that's the way it is".

Another "fact" is that "reactive power" is closely related to voltages. For this competition, and all the previous ones, we made sure that the voltages are set by the generators (so the bus at substation 0 and 1 have a fixed voltage) but not the other elements (all the others buses are not controlled and the voltage there depends on the loads and the "proximity" to the generators). [This is a common modeling: generators are called "PV" and the rest "PQ", we could make this modeling more realistic but it would add even more complexity...]

When you turn off line *0 -- 3* you not only cut the "route" *1 --> 2 --> 0 --> 3 --> 4* for the active flow, but you also change the "distance" between node at substation 3 and the closest generator (it was 1 before, now it's 2).

This should (i say "should" because i did not check) have the effect to reduce the voltage at this node (you can check it with `obs.v_or` or `obs.v_ex` or `obs.load_v` for example). Reducing the voltages will increase the reactive power that need to be "brought" there. 

This takeTthe arrows represent the direction of the active flow, but probably the "reactive flow" goes from *4 --> 3*, and so it can make the powerline *3 -- 4* more loaded because of this component. 

The "total" flow at one end of a powerline is given by the formula: `obs.a_or = sqrt(obs.p_or + obs.q_or) / (sqrt(3) * obs.v_or )` and is expressed in amps (A). So basically, you reduce the active value p_or of line *3 -- 4*, but as you also increase its reactive value q_or, you can have a increase in the current flow.

**NB** this is an illustration that tries to explain this behaviour. In no case the "electron" (or whatever else) is really "moving a direction" in an grid operated in alternating current. Nothing is really "flowing" the current has no "route", there is no "closest distance to a generator" etc. Powergrid transports energy in the form of electro magnetic waves. This simplification based on "moving particules" has of course its limitation.

**Comment by vakker** [comment]
@BDonnot thanks a lot for the detailed explanation, it helps a lot (even though I still don't fully understand it :smile: ).
