### ISSUE TITLE
Enhance notebook "2_Action_GridManipulation" to make it clear some actions presented are ambiguous

### ISSUE THREAD

**Issue by jhmenke** [rte-france/Grid2Op#27]
Notebook _2_Action_GridManipulation.ipynb_ provides the following notation for changes of line status:

```
the_same_act = action_space({"set_line_status": [(3,1), (4,1), (5,-1), (6,-1)],
                             "change_line_status": [0,1,2]
                            })
print(the_same_act)
```
If one prints this, then the description says that the statuses of lines 3,4, 5, 6 will be set accordingly. However, nothing will actually happen as the reward is the same as the one received with a do nothing action. What instead works is to have a vector with the same length as the number of lines as the value of "set_line_status". 
Setting 1/-1 at the corresponding line positions will be parsed correctly. 

This seems to be a bug.
>the_same_act = self.action_space({"set_line_status": [(3,1), (4,1), (5,-1), (6,-1)], "change_line_status": [0,1,2]})
> observation.simulate(the_same_act)
> Out[13]: 
> (<grid2op.Observation.CompleteObservation at 0x7fba9cc42f10>,
>  14.59234479485048,
>  False,
>  {})
> observation.simulate(self.action_space({}))
> Out[14]: 
> (<grid2op.Observation.CompleteObservation at 0x7fba9bd58090>,
>  14.59234479485048,
>  False,
>  {})
>

**Comment by BDonnot** [comment]
Hello,

I think this behaviour, though a bit surprising is perfectly fine. In fact, this action is "Ambiguous" (there is no unique way to understand what the user meant by this action). 

In this case, it is ambiguous because you asked to connect a powerline, without specifying on which bus. There are 4 different ways to reconnect a powerline in grid2op:

- connect it to bus 1 on origin and bus 1 on extremity
- connect it to bus 2 on origin and bus 1 on extremity
- connect it to bus 1 on origin and bus 2 on extremity
- connect it to bus 2 on origin and bus 2 on extremity

As it's not clear what you meant by "reconnecting" powerline 3 and 4, then it is not performed on the powergrid. On the real "env.step" this is tagged in the "infos" dictionnary. Il will work on adapting it to the "obs.simulate" too.

Note that this behaviour is explained in the text bellow de description of the action:
> **NB** this action is ambiguous so it cannot be implemented on the powergrid. Indeed, powerlines 3 and 4 are reconnected, but we don't specify on which bus!

The fact that the action is silently not implemented is pretty common in video games. For example, in pacman, when you face a 

I agree this makes a poor example. I will try to rework this part. I switch your issue to an enhancement on the 2nd getting started.

**Comment by jhmenke** [comment]
Thanks for the answer!

Then i find the notebook a bit confusing, at least for the change_line_status case (see other issue). The demo action does not specify that i need to define a bus for changing the status:

> the_same_act = action_space({"set_line_status": [(3,1), (4,1), (5,-1), (6,-1)],
>                              "change_line_status": [0,1,2]
>                             })
> print(the_same_act)

**Comment by BDonnot** [comment]
Indeed i will make it more explicit. Thanks for the valuable comment.

**Comment by BDonnot** [comment]
This issue has been fixed in latest version (that i'm testing for integration at the moment).
Thanks again for the feedback.
