### ISSUE TITLE
Error creating node feature matrix with as_networkx()

### ISSUE THREAD

**Issue by EloyAnguiano** [rte-france/Grid2Op#330]
## Environment
 - Grid2op version: `1.7.1`        
 - Stable Baselines 3 version: `1.4.0`        
 - System: `Ubuntu 18.04 LTS`
 - Python `3.9.12`

## Bug description
Once issue #327 is fixed in 1.7.1, I am also trying to get the node features as a matrix from the graph. But when I try to build that marix, it is simetimes of shape (5,6) and sometimes (1,6) so SB3 returns another error (check `build_feature_matrix` function).

### Command line
```bash
# python script.py
```

### Code snippet
```python

import torch as th
from stable_baselines3 import SAC
from stable_baselines3.common.torch_layers import BaseFeaturesExtractor
import gym
from grid2op import make
from grid2op.gym_compat import BoxGymActSpace, GymEnv
from copy import deepcopy
import networkx as nx
from gym.spaces import Box
import numpy as np
import torch.nn as nn
import os

warnings.filterwarnings("ignore")

def build_matrix(obs, key):
    if isinstance(obs, nx.Graph):
        graph = obs
    else:
        graph = obs.as_networkx()
    matrix = nx.attr_matrix(graph, edge_attr=key)[0].A
    return matrix

class FlatFeatureExtractor(BaseFeaturesExtractor):
    def __init__(self, observation_space:  gym.spaces.Dict, features_dim: int, device):
        super(FlatFeatureExtractor, self).__init__(
            observation_space, features_dim)

        self.device = device

        space = observation_space["rho_matrix"]
        n = space.shape[0] * space.shape[1]

        self.last_dense = nn.Sequential(
            nn.Linear(n, self.features_dim),
            nn.ReLU())


    def forward(self, observations: gym.spaces.Dict) -> th.Tensor:
        return self.last_dense.forward(observations["rho_matrix"].flatten(1))

os.environ["CUDA_VISIBLE_DEVICES"] = "0"
DEVICE = th.device("cuda:0" if th.cuda.is_available() else "cpu")

POLICY = {  "features_extractor_class": FlatFeatureExtractor,
            "features_extractor_kwargs": {
                "features_dim": 256,
                "device": DEVICE,
            },
            "activation_fn": th.nn.ReLU}

def build_feature_matrix(obs):
    if isinstance(obs, nx.Graph):
        graph = obs
    else:
        graph = obs.as_networkx()
    
    matrix = [list(graph.nodes[n].values()) for n in range(graph.number_of_nodes())]
    np_m = np.array(matrix) #HERE. sometimes np_m.shape = (5,6) and sometimes (1,6)
    return np_m

if __name__ == "__main__":

    grid2op_env = make("rte_case5_example", test=True)
    env = GymEnv(grid2op_env)  # create the gym environment

    # CHANGING ACTION SPACE
    env.action_space = BoxGymActSpace(env.init_env.action_space)

    # CHANGING OBSERVATION SPACE
    grid2op_obs = grid2op_env.reset()

    # Adding vars
    graph = deepcopy(grid2op_obs).as_networkx()

    graph_vars = {"rho":(-1000, 1000)}

    for k in graph_vars.keys():
        shape_ = build_matrix(graph, k).shape
        env.observation_space.add_key(f"{k}_matrix",
                                        lambda obs: build_matrix(obs, k),
                                        Box(shape=shape_, 
                                            low=np.full(shape_, graph_vars[k][0]),
                                            high=np.full(shape_, graph_vars[k][1])))

    shape_ = (graph.number_of_nodes(), len(graph.nodes[0].values()))
    env.observation_space.add_key(f"node_features_matrix",
                                    lambda obs: build_feature_matrix(obs),
                                    Box(shape=shape_, 
                                        low=np.full(shape_, -1000),
                                        high=np.full(shape_, 1000)))
    agent = SAC("MultiInputPolicy", env, policy_kwargs=POLICY, verbose=1)
    agent.learn(total_timesteps=1e5)

```

## Current output

```
Traceback (most recent call last):
  File "/home/user/repos/tesis-eab/src/l2rpn/src/agent_sb3.py", line 132, in <module>
    agent.learn(total_timesteps=STEPS)
  File "/home/user/miniconda3/envs/test_grid/lib/python3.9/site-packages/stable_baselines3/sac/sac.py", line 292, in learn
    return super(SAC, self).learn(
  File "/home/user/miniconda3/envs/test_grid/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 354, in learn
    rollout = self.collect_rollouts(
  File "/home/user/miniconda3/envs/test_grid/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 602, in collect_rollouts
    self._store_transition(replay_buffer, buffer_actions, new_obs, rewards, dones, infos)
  File "/home/user/miniconda3/envs/test_grid/lib/python3.9/site-packages/stable_baselines3/common/off_policy_algorithm.py", line 507, in _store_transition
    next_obs[key][i] = next_obs_[key]
ValueError: could not broadcast input array from shape (1,5) into shape (5,6)
```

**Comment by BDonnot** [comment]
Hello,

This is totally "normal" the size of the "matrices" `obs.as_networkx()` and `obs.flow_bus_matrix()` and `obs.bus_connectivity_matrix()` is not fixed. The size can vary between the steps in a single episode.

More information is provided here: https://grid2op.readthedocs.io/en/latest/grid_graph.html#how-to-retrieve-the-graph-in-grid2op and summed up in the table there.

Basically, in this case, when the grid is "game over", there is no "bus", so no "graph" (this was what caused the issue you mentioned : this "fact" was not properly taken into account). 

To "circumvent it" i chose to have a graph with a single node in this case with everything connected to this single node. This is why you get a size of 1.

I'm not sure what I can do in this case, but definitely if you use "obs.as_networkx(...)" your agent somehow should deal with observation with varying size.

**Comment by EloyAnguiano** [comment]
Hi, 
I think I still don't get it. This is my test power grid:
![episode_view_easy](https://user-images.githubusercontent.com/17010375/173064080-63cbc818-1ee8-4105-bb9f-bfcd46af5c25.gif)

When I get the graph (the "normal" graph), it says that I have 5 nodes, which I assume that those are the 0-4 substations on there, not the buses like the documentation says. 

I think that what you are trying to say is that when every connection (powerline) at the graph are removed, you only have a node, but this is not true. You still have a graph with 5 nodes that are not connected to any other. 

Addicionally, when I get the graph using `obs.as_networkx()` it returns a `networkx.classes.graph.Graph` which I think its not correct. As we can see at the example, between substations 2 and 3 there are two connections, so I think it should be a [MultiDiGraph](https://networkx.org/documentation/stable/reference/classes/multidigraph.html) object. Indeed, there are 2 types of buses to conect the edges so it encourages more this need.

**Comment by BDonnot** [comment]
Hello,

>  I assume that those are the 0-4 substations on there, not the buses as the documentation says.

I think the documentation is right but lack (clearly) some explanation. But I totally see your point.

## The "normal" graph

In power system "the" power grid graph (the one you get with `obs.as_networkx()`) is the one (by definition) with:
 - node = bus (= activated bus, if a bus is disconnected it's not present, if there are 2 buses at a substation, then there are two corresponding nodes)
 - edges = link between buses, that translates to powerlines  / transformers

This is the graph called "normal" graph in grid2op and this is the one returned by "obs.as_networkx()". It returns a "normal" graph from networkx because it is a "normal" graph (basically, unless there is a bug somewhere) the flows are summed up if there are parrallel powerlines for example:

```python
import grid2op
env = grid2op.make("rte_case5_example", test=True)
obs = env.reset()
graph = obs.as_networkx()

graph.edges[(2, 3)]
# {'p': 11.868799, 'p_or': 11.964334, 'p_ex': -11.868799, 'q_or': -38.829334, 'q_ex': 36.100735, 'a_or': 230.12498, 'a_ex': 215.32852, 'theta_or': -1.1422914, 'theta_ex': -1.4185632, 'rho': 0.38354164, 'cooldown': 0, 'status': True, 'thermal_limit': 300.0, 'timestep_overflow': 0}

obs.p_or
# array([-9.71928   , -2.4419413 ,  0.11702504,  3.9441967 , 15.596751  , 5.982167  ,  5.982167  ,  3.8972213 ], dtype=float32)
```
As you see above, in the graph you got an active power of `11.964334` and this corresponds to the `obs.p_or[[5,6]].sum()`: `5.982167 + 5.982167` which is the active power for all powerlines connecting bus id 2 to bus id 3 [in this case, the bus 2 is the first bus of the substation 2 and the bus 3 is the first bus of substation 3, bus this is a (handy) convention which does not hold all the time] 

This represents the graph "as seen by the electricity". Is this clearer what this function does ?

## What I understood you wanted

As I understood, you would like a graph, with:
- node = busbars (whether it's connected or not, so always 2 nodes - of this graph- per substation, this graph could have nodes without any incoming / outgoing edges)
- edges = powerlines connecting these buses (so always `type(env).n_line` edges)

Is that what you would like ?

If so you have all the information of that in the observation directly. You know on which "busbars" each element is connected (including the "lines" at both their side) with the `obs.***_bus()` (*eg* `obs.load_bus` or `obs.line_or_bus`) to "easily" build this graph. This is why i did not put it in grid2op. But apparently I was wrong and it could have helped some people.

This would take, as you mentionned, the form of a "networkx DiGraph" and I see it more a "feature request" rather than a bug. 

I totally understand this type of graph can be interesting for lots of application, but i'm afraid it's not what the "`obs.as_networkx()`" returns. Let me know if you want this type of graph, and of course, any pull request in this direction is welcome :-)

Until the next L2RPN starts, I'm afraid I will not be able to code this function.

ps: the `obs.networkx()` graph is a "reduction" of the graph described here with to connex, without multi edges graph:
- all nodes without incomming / outgoing edges are removed (this corresponds to the "disconnected bus")
- all parrallel edges are agregated into one single edge
