### ISSUE TITLE
Improve the "as_networkx()" method

### ISSUE THREAD

**Issue by BDonnot** [rte-france/Grid2Op#334]
It could benefit a bit of optimization to make it faster.

In the nodes attributes, we could add different type of information such as:
- the substation to which this node belong
- the `id` (1 or 2) of the busbar it represents
- add some attributes such as the gen_max_ramp_up for example

And for the edges:
- the id(s) of the lines it represents
- labelling which powerline or (or ex) is the "or" of this edges
- better identifying the number of power the edge represents
- clean some of the attributes (cooldown = max of cooldown, and rethink all the others, if that make sense)

**Comment by EloyAnguiano** [comment]
I have a doubt in this regard. The graph returned by this method is a generic graph (Graph object class), but then in the attributes of the edges variables of the form x_or and x_ex are specified, implying that those edges have a directionality and therefore it is a directed graph (Digraph). Indeed, it should be a MultiDiGraph as some nodes may be connected by two edges. I am concerned that this convention of origin and destination is a sign convention without putting directionality in the graph, since there could be equivalence between different graphs.

On the other hand, I do not understand how it is the substations that have generation and load attributes, when it would make more sense to include it as a node attribute of those fictitious nodes that are generated in this network.

It is possible that the answer to my questions is documented in some way but I have not found the reference, so if you could at least provide it I would be very grateful.

**Comment by BDonnot** [comment]
Hello,

For the `graph` / `digraph` / `multi digraph` argument you are, in a sense totally correct from a certains point of view. When the powerflow is computed, for the sake of the computation, powerline are "directed" they have an "origin" side and an "extremity" side (different solver will chose different conventions, results will be the same, only the signs will change).

This, in my opinion, is a modeling "artifact" in reality a powerline is "just" a piece of metal, it's a cable perfectly symmetrical. This is why I chose to code it as a normal graph. I definitely see your point though and it could make it clearer to have a "multi digraph" I totally agree.

Maybe I could do two ways to convert it as a graph. I am not clear on this topic to be honest.

**Comment by BDonnot** [comment]
For the second comments about the loads / generators it all comes down to commonly used representations in power systems.

In reality, there is no "load" nor "generator" connected directly at high voltage or very high voltage to a grid.

A load is indeed another grid operated at lower voltage levels (often by a DSO)band connected to the grid represented in our problems thanks to a transformer (so a "powerline" in grid2op). And for the sake of simplicity this whole "sub grid at lower level" is represented as a single element, a "load" and it is modeled as something that consumes power from the grid, this "power consumed" is the power flow in the transformer connecting the subgrid to the grid.

For the generation is it similar (though a bit different) but basically it's also a transformer connecting a power source to the grid. And for the sake of simplicity, only the power injected in the grid in the transformer connecting the "real generator" is represented as a "generator"


This is why generator and load are directly connected to buses and are "part" of a substation. Their attribute are nodes attributes.

**Comment by EloyAnguiano** [comment]
About what you say about making different ways to obtain a graph, I think it is not the right approach. The function itself should return the most informative object possible (MultiDiGraph), and in case someone wants to simplify it he can always do a casting to have an undirected graph, but it can never be done the other way. I understand that the direction convention of the graph is arbitrary, but the convention that has been followed should be reflected in the graph.

On the other hand, about the generators and the loads of the electrical network I understand that many times it is another network, but I only indicated that those attributes should appear in each of the fictitious nodes of the conversion to network, but according to what you comment it should already appear as such so I must have something in my code that does not filter because I do not see it in the node attributes after the conversion to network.

**Comment by EloyAnguiano** [comment]
Also, I miss a lot of the attributes of the [BaseObservation](grid2op.readthedocs.io/en/latest/observation.html#grid2op.Observation.BaseObservation) when you make `obs.as_networkx()` such as `gen_p`, `load_p`, `storage_p`, `gen_q`, etc. at node attributes. Is there a simplification there such as `p = gen_p - load_p - storage_p` or something like that?

**Comment by EloyAnguiano** [comment]
Thanks a lot for the modifications made to the network in the commit, it really helps. For backward compatibility issues this network could be like this, but I think you could add a flag that by default is False, but if you set it to True it will return the most informed network possible. Something like `obs.as_networkx(full=True)`.

This means that it would return a MultiDiGraph (since some variables indicate direction, such as p_or or p_ex and there can be several connections between the same nodes), and also the rest of variables not simplified (such as gen_p, load_p, storage_p) since these could be modeled individually for an agent in production. 

I would like to make these modifications myself but I have been trying to understand the code for this particular function and I am not getting my head around it, so it would be helpful if you are able to do this. If you need anything I can help you with I'd be happy to do so.

**Comment by BDonnot** [comment]
Hello,

I modified today the "as_networkx" method. You can install it from github, on the branch dev_1.8.2 if you want to have a test.

This is still using the current "graph", which is the graph that the "electrons", the "power", the "energy" are seeing. 

To include all grid2op data, I will do something a bit differently, but from which you can do a "multi digraph" if you want. What I will do is the "full complete directed graph" (name subject to change of course ;-) ) which is basically all elements will be nodes of this graph. So you will have "nodes" of different types: 
- some nodes will be `substation` to which some `bus` will be connected (thanks to edges, so edges have a direction meaning 'is connected to').
- some other nodes will represent `bus` to which some `element` will be connected: edges coming in a node representing a bus will reference all power system elements that are connected to a bus. The edge going out from a node (still representing a bus) will represent the substation to which this bus is connected to.
- some other nodes will represent `loads` and they will have attribute such as `p`, `q` and `v` (all that is in load_p, load_q and load_v in the observation basically) and the will be connected to `bus` thanks to an edge. I'm still hesitating: do I put the attribute (p, q, v, a) in the elements itself (so in the load in this case) or in the edges that connects this element to its bus.
- same for generators and shunts and storage units etc.

For the powerlines it works similarly except from the node representing the powerlines, you have 2 outgoing edges, one for each side of this powerline. And this might be why the attribute (p, q, v a) should probably be for the edges and not for the element (no more probleme between "or" and "ex" if they are directly on the relevant edge)

Let me know what do you think

**Comment by EloyAnguiano** [comment]
That seems a very good and generic approach. That way anyone could make the desired graph from that one.

**Comment by BDonnot** [comment]
Nice :-)

You can find better docs here: https://beta-grid2op.readthedocs.io/en/bd_dev/grid_graph.html#graph2-the-elements-graph (I still need to perform some tests to make sure everything works as intended) and install from github there https://github.com/BDonnot/Grid2Op/tree/bd_dev

(if you want to test it asap)

In any case, it will be present in the next grid2op release.

**Comment by EloyAnguiano** [comment]
Hello again, sorry for the delay. I have been testing the new full graph functionality you offer and it does leave a lot more freedom to deal with the problem at hand. To clarify, I am doing visualizations of each of the environment powergrids. With those visualizations I have obtained the following graph for the rte_14_dispatch test environment.

![complete_graph](https://github.com/rte-france/Grid2Op/assets/17010375/867f1ebc-5527-40a6-b053-4af8eebb5ae1)

In this graph you do see each of the elements colored with the type of node they belong to. However, I am particularly struck by node 45, which is a "load" node and is connected to a node of type "bus" (expected behavior) but is also connected to a node of type "line", which I do not know if it is entirely possible. How can that happen, is it the expected behavior?

**Comment by EloyAnguiano** [comment]
Sorry, while I was making the reproducible example I could check that those nodes are not connected. It seems to be a plotting issue:
![complete_graph_mistake](https://github.com/rte-france/Grid2Op/assets/17010375/fbf59047-d433-460a-b1fc-e627e6551889)
If you experienced this issue maybe it is a plotting issue too.

**Comment by BDonnot** [comment]
Nice to see there's no bug there 😊

**Comment by EloyAnguiano** [comment]
Hi again, I am working with this new way to see the powergrid as a graph and the truth is that it is very useful. However, to make it completely correct I would like to make a few suggestions for improvement to make it as understandable as possible:

As you can see in the image above, there is a particularity of the graph that jumps out at first sight, and that is that there are a few bus nodes that are disconnected from the graph. These buses actually do have topological location, although they are disconnected. Therefore, I think that the correct thing to do would be to connect them with the corresponding substation, but taking advantage of the attribute "connected" (setting it to False) that you have created very conveniently in each of the nodes of this network. 

It is even possible that the "connected" attribute makes more sense to put it in the edges than in the nodes themselves, since it is the edge that has a state of "activated" or "not activated", but that is simply a formalism that is not necessary to treat since it can be done with a postprocessing without problems.

**Comment by BDonnot** [comment]
Hello,

Thanks for the feedback.

When I coded it I hesitated between different things, among them what you proposed.

For the buses, the outgoing edge represents "is part of" (it's a different nature than the other edges) and I think you're correct, it makes more sense to always have the edges (because even if it's disconnected the bus is still "part of"). Or maybe I can remove the substation information and the disconnected buses (but in that case the graph can vary in size so it's probably not that a great idea)

For the location of the "connected" attribute I put it in the node an not in the edge because it's easier this way to know if it's connected or not just by looking at the node (otherwise you have to know if there are outgoing edges). I thought it should not be an edge attribute because it would be always "True" (otherwise there is no outgoing edges of I remember correctly). But as you said it's a matter of convention (and in this case convenience : you can know if a node is connected or not just by looking at the node (at not the edges)) 

Thanks for the feedback, can you write a quick feature request with the bus - substation part? Thanks 😊

**Comment by BDonnot** [comment]
New proposed "graph" seems to do the job just fine for now. I'm closing this original issue :-)
