### ISSUE TITLE
Question: What assumptions does backends objects make to simplify simulation?

### ISSUE THREAD

**Issue by EloyAnguiano** [rte-france/Grid2Op#353]
Hi all, I have a question and in this repository there is no template to make a question so I choose to do it freely. 

As far as I am concerned, the simulations of electrical systems are quite heavy, and the currently most used software is PSS/E (https://en.wikipedia.org/wiki/Power_system_simulator_for_engineering). This software is characterized by being a heavy software that takes quite a long time to do simulations of electrical systems. 

However, in the Grid2Op library there are different Backend objects that do this simulation work in more or less time, but certainly not of the order of the computational complexity that running PSS/E can entail. This leads me to reason that there are certain simplifications by which these Backends may not be as accurate as the software mentioned, but they do the job in a similar way. 

If that is the case, I would like to know what simplifications or assumptions are made to be able to run these simulations in reasonable times, and if not I wonder how such software can be so popular if there are faster alternatives.

Thanks in advance

**Comment by BDonnot** [comment]
Hello,

Thanks for the interesting question that raises lots of different topics about power system simulation.

I'll try to be concise. Know that I'm not from a power system background, so my answers might be a little bias.


First, and most importantly "all models are wrong, some are useful". What do I mean by that?

There are lots of different models to simulate a grid depending on what you want to do. For example when you look a problems like "in 50 years, will this new powerline be still useful for the grid" (typical question of grid development and planning, a powerline lasts at least 50 years) your "errors" will be mainly due to the "hypothesis for the future" that you make (how people will consume energy, where, with which devices etc) so it does not really make sense to use super fancy high fidelity simulators. And even if you wanted, you probably wouldn't have the data to do so.

Un the other direction, sometimes you might need to run some really fine grained simulator that takes into account dynamics phenomenon. Basically you solve some partial differential equations derived from Maxwell equations with more or less accuracy.

All of that to say that for grid2op, the 2 available backends (pandapower and lightsim2grid) uses the same types of hypothesis : it assume the frequency is known, constant and that finds a "steady state" solution of the equations. As far as I know it's the main model used today real time operations of power grid. I suspect that the software you mention does the same types of computation.

And even there, "the devil is in the details":

1) These steady state model (called load flow or power flow) can be  "model" more or less equipment on the grid. For lightsim2grid, no "fancy" objects are modeled: no DC powerline, no 3 windings transformers etc. 

2) Lightsim2grid makes the hypothesis of a powerflow. For example a generator either control the voltage (and has all the "juice" it needs to do so) or inject a fix amount of "reactive" power on the grid. In reality it's more complicated, there are some limit to the "juice" a generator can have. 

3) some physical properties, for example the resistance, reactance, transformer ratio are assumed fixed in lightsim2grid. In reality there might be sometimes some ways to modify these properties and some "automaton" do that in real time. 


Industrial software are able to emulate a "somewhat realistic in most cases" these "fancy" elements and behaviors (I cannot do an exhaustive list) which slow them down. We don't bother doing it so we're faster.

**Comment by BDonnot** [comment]
As for the speed, the grid2op usage is 'it the typical usage of "power grid simulators"

In typical grid study, you have a few grid states (usually just one) and you do an extensive study of "what would happen if this, this or this" (typically "what would happen if a powerline would disconnect", and you do that for all powerlines). And modern software are optimized for that purpose.

Also keep in mind industrial software are tailored towards industrial usecase. Which often involves grids with thousands, ten of thousands or even hundreds of thousands buses (instead of ~100 for the largest available grid in grid2op).

So the problem is not so much optimizing computation speed to load or modify a single grid state marginally. But to load one big grid, and then do heavy computatioon on this grid.


For lightsim2grid I spend some times to optimized the copy, rely on (super) fast available linear solvers (that might not be usable in commercial software due to license issues, etc) and are tailored to grid2op-like usecase.

Finally, lightsim2grid / grid2op (and all the ecosystem) are research oriented softwares. Developed mainly by myself, with very limited support and a small "capacity to evolve", developed by a non expert in numerical simulation nor power grid (myself) .

Most companies operating the grid would need to rely on heavily tested and resilient software, heavily maintained etc. They don't  need the software alone, they also wants the services and maintenance of such software.


I hope I answered the questions. Let me know if I can further assist you 😊

**Comment by BDonnot** [comment]
Oh and also there are some alternatives to pss/e such as :

- power factory (non open source)
- hades 2 (used at RTE for example, available there https://github.com/rte-france/hades2-distribution)
- open load flow (OLF, maintained by the Linux Fundation) 
- gridcal 
- grid pack (specialized in HPC and super large grid) 
- pandapower
- matpower (one of the research favorite, in Matlab) 
- dynawo (different simulators for time domain simulation) 
- power models (focused on optimization, in Julia)

Etc etc

All have pros and cons and made some different assumptions about the grid and are more suited for this or that use case 😊

**Comment by EloyAnguiano** [comment]
Wow, thank you very much for responding in such a short time and in such a clear way. I will try to digest all this information little by little and if I have any doubts I will reopen this issue, but for the moment I will leave it closed in the meantime thanks to your great explanation.

Thank you very much
