### ISSUE TITLE
Inconsistent thermal limits in env and obs from env.get_obs()

### ISSUE THREAD

**Issue by marota** [rte-france/Grid2Op#356]
## Environment
 - Grid2op version: `1.6.5 & 1.7.2`
 - System: `ubuntu20.04, ...`
 - Additional system information

## Bug description

When getting an observation through env.get_obs(), thermal_limits don't have a consistent value with the ones from env. Then obs.rho does not have expected value either, which then causes issues when relying on that variable

### Command line

```bash
# command line used if any 
```

### Code snippet

```python
from grid2op import make
env=make("l2rpn_case14_sandbox")
obs=env.get_obs()

assert all(obs.rho==obs.a_or/env.get_thermal_limit())
assert all(env.get_thermal_limit()==obs._obs_env.get_thermal_limit())

```

**Comment by BDonnot** [comment]
This "bug" seems only to appear when the `env` has not been "reset" which is not really supported: always use `obs  = env.reset()`  at least once before using an environment.

I tag it as an "improvement" because i'm pretty sure something can be done to fix this particular issue (even when the env is not properly initialized).

The valid code:

```python
from grid2op import make
env=make("l2rpn_case14_sandbox")
obs=env.reset()

assert all(obs.rho==obs.a_or/env.get_thermal_limit())
assert all(env.get_thermal_limit()==obs._obs_env.get_thermal_limit())
```
works on my machine
