### ISSUE TITLE
gen_max_ramp_up is ignored when there is a topology action but no redispatch action

### ISSUE THREAD

**Issue by richardwth** [rte-france/Grid2Op#368]
## Environment
 - Grid2op version: `1.7.2`
 - System: `ubuntu18.04`

## Bug description
When there is no dispatch action on any generator, the `gen_max_ramp_up` constraint may be ignored.

## How to reproduce
```
from grid2op import make
from lightsim2grid import LightSimBackend

backend = LightSimBackend()
env = make("l2rpn_wcci_2022", backend=backend)
action_space = env.action_space

env.set_id(2)
obs = env.reset()
# note the forecast gen_p is larger than current gen_p + gen_max_ramp_up
print("init:", obs.gen_p[2], 'forecast:', obs.get_forecasted_inj()[0][2], 'gen_max_ramp_up: {:.1f},'.format(obs_.gen_max_ramp_up[2]))

# set up any topology action, e.g., 
# connect all elements in substation 1 to bus 2
sub_id = 1
action = action_space()
nb_el = type(action_space).sub_info[sub_id]
arr_ = np.full(nb_el, fill_value=True, dtype=bool)
action.sub_change_bus = [(sub_id, arr_)]

# simulate this topology action; note gen_p increases by 8.7, larger than gen_max_ramp_up
obs_, _, done, _ = obs.simulate(action)
print('simu: {:.1f},'.format(obs_.gen_p[2]), 'actual_red: {:.1f},'.format(obs_.actual_dispatch[2]), 'target_red: {:.1f}'.format(obs_.target_dispatch[2]))
```

## Current output
```
init: 356.7 forecast: 365.4 gen_max_ramp_up: 3.5
simu: 365.4, actual_red: 0.0, target_red: 0.0
```

## Expected output
```
init: 356.7 forecast: 365.4 gen_max_ramp_up: 3.5
simu: 360.2, actual_red: 0.0, target_red: 0.0
```
However, this bug can be avoided if a small redispatch is applied on any redispatchable generator, e.g.,
```
small_redispatch = action_space({'redispatch':[(37, 0.01)]})
obs_, _, done, _ = obs.simulate(action + small_redispatch)
print('simu: {:.1f},'.format(obs_.gen_p[2]), 'actual_red: {:.1f},'.format(obs_.actual_dispatch[2]), 'target_red: {:.1f}'.format(obs_.target_dispatch[2]))
```
leads to
```
simu: 360.2, actual_red: -5.2, target_red: 0.0
```

**Comment by BDonnot** [comment]
Hello,

You are totally correct, this is a difference of behaviour caused by:
1) speed optimization in grid2op: the redispatching routine is not called when there has not been any redispatching / curtailment / storage
2) the hypothesis that the input data meet the max_ramp_up / max_ramp_down / pmin / pmax for all generators.

Clearly, for the forecasts, in this case, the point 2 above is not met (as you showed).

And if you do not do any redispatching, the environment will "not" compensate (point 1 above) for this error. But if you did some redispatching at some point, the redispatching routine will be called and the results you get will meet the max_ramp_up / max_ramp_down / pmin / pmax 

There is nothing "harmless" I can do about it right now [I would need a much much faster redispatching routine to not code the safety guard in 1) ]. 
I will document it however in the "obs.simulate" docs and make it clear that "simulate" is only an approximation that does not do exactly the same as the `env.step` one example is this specific case.

Thanks for investigating this issue.
