### ISSUE TITLE
obs._obs_env._thermal_limit_a / obs._obs_env.backend.get_thermal_limit() not correct in case14_realistic

### ISSUE THREAD

**Issue by jhmenke** [rte-france/Grid2Op#38]
The values transmitted via *obs._obs_env.backend.get_thermal_limit()* are those of the old case14 grid with nonsense thermal limits. 

The values from *env._thermal_limit_a* need to be propagated correctly before the simulation starts.

**Comment by BDonnot** [comment]
Hello,

This issue, though i forgot to note it on the changelog and to point it out when i made the release has been fixed in the latest (0.5.8) release #45, and we made some more tests concerning the "simulate" function to ensure it won't appear again (hopefully).

If this release fixed the issue, feel free to close it. Otherwise i'd be happy to further discuss it

Thanks

Benjamin

**Comment by jhmenke** [comment]
works now
