### ISSUE TITLE
Plausible values for transformer's rated power

### ISSUE THREAD

**Issue by jhmenke** [rte-france/Grid2Op#48]
Currently, all transformers have a rated power of 9900 MVA in the pandapower backend grid. 
Parsing

`grid.trafo["max_i_ka"] = obs._obs_env._thermal_limit_a[len(self.grid.line):] / 1000.`

and using the following formula to generate a more plausible *sn_mva*

`np.sqrt(3) * self.grid.bus.loc[self.grid.trafo.hv_bus, "vn_kv"].values * self.grid.trafo["max_i_ka"].values`

i get:

> Name: sn_mva, dtype: float64
> 0     92.000000
> 1     55.200000
> 2     40.825000
> 3     82.500000
> 4    117.857143

This seems much more realistic, however, transformer 2 is overloaded in the first timestep (44 MW vs. 40.8 MVA limit). The *max_i_ka* value is very low:

> 0    0.384900
> 1    0.230940
> 2    0.170799
> 3    3.402243
> 4    3.402243
> Name: max_i_ka, dtype: float64 

I noticed the issue comes from the vk_percent value of the transformers, which are much too high. Typical values are below 1 %, however the initial values are > 1000 %. After normalizing them somewhat by

`self.grid.trafo["vk_percent"] /= 1e4`

the power flow converges. But now, the loading percent is still much too high:

> 0    252.237821
> 1     89.102943
> 2    389.214114
> 3    233.745565
> 4     36.207367
> Name: loading_percent, dtype: float64

_How were the thermal limits chosen? Can they be integrated into the pandapower grid more naturally?_

The initial problem was the Backend says a transformer is overloaded in timestep 801 (*set_id(0)*), but the agent's pandapower results showed no overloading.

If i adjust the *sn_mva* values to more realistic values and increase them to not have transformer overloading, then the grid's power flow characteristics change completely. 
As a second option, i can calculate if a transformer is overloaded manually by using the resulting transformer currents and dividng by the backend's thermal limits. I can get plausible values this way, however, then transformer loading cannot be used while performing optimal power flow.

**Comment by jhmenke** [comment]
A workaround is the following:

```pp.runpp(self.grid)
self.grid.trafo["max_loading_percent"] = 0.95 * self.grid.res_trafo.loading_percent.values / self.grid.res_trafo.i_hv_ka.values * self.grid.trafo.max_i_ka.values```

The maximum loading percent is scaled according to an initial power flow. No trafo sn_mva values need to be adjusted then.

**Comment by BDonnot** [comment]
Hello Jan Hendrick :-)

I didn't want to modify too much the grid initially loaded, that is why the thermal limit are provided in an external vector, outside of the pandapower grid. You can use the:
backend.thermal_limit
or
env._thermal_limit

Transformers are considered as powerline, because, from a ML perspective, trafo pass the "[Duck Test](https://en.wikipedia.org/wiki/Duck_test)": they have flows like a powerline, limits (usually in current) like a powerline, 2 ends like a powerline and can be disconnected like powerlines. So from the perspective of a user of grid2op, trafo are powerlines.

However, as you noted, changing SN_MVA in transformer will change their physical properties (the one that are used in the ppc / ppci). So better not touch pandapower in this case, and use a check in post processing to see if the flow on the transformer is ok or not :-)

Benjamin
