### ISSUE TITLE
For 1.9.2

### ISSUE THREAD

**Issue by BDonnot** [rte-france/Grid2Op#481]
- [ ] scoring class for alert (based on AlertReward)
- [ ] ~~scoring class for counting alert~~
- [x] add the possibility to return the number of "accurate simulator" used in the scoring (see the extra runner kwargs added in 1.9.0 or 1.9.1) 
- [x] add desc of the env in https://grid2op.readthedocs.io/en/latest/available_envs.html#description-of-some-environments
- [x] in  _newRenewableSourcesUsageScore.py line 59 when agent dies first step, we divide by 0
- [x] investigate possible dramatic slow down when agent uses simulate !

**Comment by GoubetClem** [comment]
Documentation review 
page https://grid2op.readthedocs.io/en/dev_1.9.1/observation.html

[] in https://grid2op.readthedocs.io/en/dev_1.9.1/observation.html#observation link to L2RPN (typo l2RPN to L2RPN + link to 2023 instead of 2022 ?)
[] https://grid2op.readthedocs.io/en/dev_1.9.1/space.html#grid2op.Space.GridObjects.dim_alerts not working nor even mentionned in obs attributes page
[] https://grid2op.readthedocs.io/en/dev_1.9.1/space.html#grid2op.Space.GridObjects.dim_alarms TO DO
[] in add_act(act, issue_warn=True) of https://grid2op.readthedocs.io/en/dev_1.9.1/observation.html#main-observation-attributes Return type: grid2op.Observation.Observation no link
[] in classgrid2op.Observation.CompleteObservation 28. missing link at BaseObservation.n_line
[] same class 31. grid2op.Space.GridObjects.dim_alarms no link
[] same class 50. BaseObservation.last_alert no link
[] same class 51.  TODO = DONE  idem 52 54 55
[] same class 53. BaseObservation.total_number_of_alert missing link
[] in class classgrid2op.Observation.ObservationSpace, arg rewardClass cite grid2op.BaseAgent.BaseAgent missing link
[] same class arg reward_helper grid2op.Reward.HelperReward missing link
[] same class arg obs_env _ObsEnv missing link
[] same class method __init__ grid2op.Environment.parameters & grid2op.Environment.backend missing link

**Comment by GoubetClem** [comment]
Documentation review:
page https://grid2op.readthedocs.io/en/dev_1.9.1/grid2op.html#modeling-the-interaction-with-operators

- [ ]  Alerte feature : attribute grid2op.Observation.BaseObservation.total_number_of_alert no link
- [ ]

**Comment by GoubetClem** [comment]
Documentation review
page https://grid2op.readthedocs.io/en/dev_1.9.1/gym.html

in [Some already implemented customization](https://grid2op.readthedocs.io/en/dev_1.9.1/gym.html#id6)
- [ ] converter add_key typo and loop link
- [ ] converter keep_only_attr typo and loop link
- [ ] converter ignore_attr typo and loop link

 in Gymnasium vs Gym
- [ ] at Default Class `_BaseGymSpaceConverter` no link
- [ ] at class with gymnasium _BaseGymnasiumSpaceConverter no link
- [ ] at class with gym `_BaseLegacyGymSpaceConverter` no link

In Detailed documentation by class
table summary
- [ ] at line DiscreteActSpace `MultiDiscreteActSpaceGymnasium` no link
- [ ] at line DiscreteActSpaceGymnasium `MultiDiscreteActSpaceGymnasium` no link

class details
- [ ] at DiscreteActSpace  "alias of MultiDiscreteActSpaceGymnasium" missing link
- [ ] at DiscreteActSpaceGymnasium "alias of MultiDiscreteActSpaceGymnasium" missing link
- [ ] at GymnasiumActionSpace gym.spaces.Dict no link 
- [ ] same class GymnasiumActionSpace have grid2op.Environment.Environment.seed() no link
- [ ] idem at class GymnasiumObservationSpace
- [ ] idem at class LegacyGymActionSpace
- [ ] idem at class LegacyGymObservationSpace

**Comment by GoubetClem** [comment]
- [ ] "mettre une erreur plus claire quand gym et gymnasium ne sont pas installés"
