### ISSUE TITLE
Different size output for observation.to_json() and observation.to_dict()

### ISSUE THREAD

**Issue by Rkaddah** [rte-france/Grid2Op#509]
When trying to see the observation size using env.obersevation_space.size_obs(), I get 1432.
When trying to export using .to_dict(), I get the same size but obs.to_json() gives more output (mainly the thetas). I enclosed an image showing the summary of attributes I get using each function. I use grid2op version 1.8.2.dev4.

<img width="532" alt="values_summarised" src="https://github.com/rte-france/Grid2Op/assets/125461833/cb2cdef1-d230-4c59-b3ca-b333daf4fe93">

**Comment by BDonnot** [comment]
Hello,

Yes you are correct, you have more data in an object of type observation (namely the thetas, the shunts etc.) compared to what is available to the observation as converted to a vector.

This is mainly due to historical reasons (so basically no reason at all...) but  also because some backend might not support the output of the `thetas`. And when that is the case, we want the observation (as a vector) to be still usable.

If you want the complete list of attributes present in "obs.to_dict()" you can have it with `type(obs).attr_list_vect` and if you want the list of attributes present in the `obs.to_json()` you can do `type(obs).attr_list_vect + type(obs).attr_list_json`

It's not really a bug that 2 different functions output two different results. This is rather a missing documentation issue, which i'll fix ASAP.
