### ISSUE TITLE
Start Episode / Scenario with Specific Topology

### ISSUE THREAD

**Issue by DEUCE1957** [rte-france/Grid2Op#636]
## Problem
In order to change the topology of a Grid2Op Environment it is necessary to use a topology-changing action (set_bus, set_line_status, etc.). This is great for if we want our agent to learn to manipulate the grid topology to improve operation. However, if we want the agent to learn to adapt to different initial conditions of the topology (but still using the same grid) this does not work well.

## Solution
An ideal solution might be to have a file in the folder for that episode which specifies either the initial topology (less ideal since then we'd need many grid.json files) or the action(s) needed to reach that topology (better, can put it in env.action_space().to_json() format), and executes that change before the episode starts (i.e. takes 0/1 timesteps to do it).

## Alternatives
A hacky way to solve this might be to perform the topology changing action at the start of the episode (might take multiple timesteps since we can only modify one substation at a time) either in place of the agent or using some custom opponent. 

Edit: A neater way is to use env.reset(options={"init state":env.action_space({"set_bus":[(...)]}) }, which will perform an action to initialize the state of the grid and appears to ignore environment parameters.

## Additional context
Want to evaluate specific (manually created) scenarios to validate the agent's behaviour. Additionally would like to be able to procedurally generate these.

**Comment by BDonnot** [comment]
Hello,

The documentation is lacking on this regard (let me know where you look for it and did not find it so that I can properly add it in the correct place).

You have multiple ways to do that right now (with direct grid2op support), for recent grid2op versions :

- in the runner, by passing the `init_states` kwargs in the `runner.run` function
- in the runner, by passing appropriate `reset_options` (ie list of dict with key `init state`)
- with a direct control on the `env.reset` call as explained here https://grid2op.readthedocs.io/en/latest/environment.html#grid2op.Environment.Environment.reset
- if you are using defaults "chronics reader" (for example `GridStateFromFile`) or if you don't really know what this means (in this case this means you are using default things so that's good for you :-) ) you can add a `init_state.json` in the folder where the data for each time serie is stored (json describing the action you want to do). This action will be applied at the beginning of each scenario (using this time serie)

With all of the above, you might want to specify your action using a dictionary (for example `env.reset(..., options={"init state": {"set_line_status": [(0, -1)]}})`

I would consider it a good practice to define the action with the names of the elements (rather than their id). The "initial state" action should only set_bus or set_status :  change_bus and change_status are deactivated (you cannot change something that is not yet defined obviously)

If you are using older grid2op versions and are ok to skip some stuff you can also do some things like what you suggest. Or even use an "opponent" for that. But I would advise to use one of the solution above and update grid2op instead :-)

**Comment by DEUCE1957** [comment]
I did stumble across the reset(option={"init_state":...}) option in the documentation here after posting this suggestion:
[https://grid2op.readthedocs.io/en/latest/environment.html#grid2op.Environment.Environment.reset](https://grid2op.readthedocs.io/en/latest/environment.html#grid2op.Environment.Environment.reset)
But had to try it out in a Jupyter notebook to see how it worked, so indeed some documentation there might help.

That there is already an 'init_state.json' for GridStateFromFile is excellent and exactly what I needed!

**Comment by DEUCE1957** [comment]
Hi Benjamin,

I am using the environment "l2rpn_wcci_2022" (since it has storage units) which uses the MultiFolder chronics class. Does the "init_state.json" only work for GridStateFromFile or also for MultiFolder? 

I use an earlier grid2op.make("l2rpn_wcci_2022") environment to create the initial action that is saved in the Chronics folder. This consists of the following action (disconnects storage unit "storage_22_0"):
```python
env.action_space({"set_bus":[(99,-1)]})
```

If I convert this to json and dump it:
```python
init_state_act = env.action_space({"set_bus":[(99,-1)]})
with open(scenario_folder_path / "init_state.json", "w") as json_file:
    json.dump(
        init_state_act.to_json(scenario_folder_path / "init_state.json"),
        json_file, indent=4,
    )
```
I get the "init_state.json" folder in the chronics directory of scenario "2050-01-03_0" (arbitrarily chosen, just to test).

However, if I then create the environment and load that specific episode:
```python
from grid2op.PlotGrid import PlotMatplot
env = grid2op.make("l2rpn_wcci_2022")
env.set_id("2050-01-03_0")
obs = env.reset()
print(env.chronics_handler.get_name()) # Confirm correct episoe
PlotMatplot(env.observation_space).plot_obs(obs);
act = env.action_space() # {"set_bus":[(env.storage_pos_topo_vect[0], -1)]})
obs, reward, done, info = env.step(act)
PlotMatplot(env.observation_space).plot_obs(obs);
```
I get a bunch of warnings (but no errors) and (from the plotting) it appears the initial state was not used.

The warnings (just showing one since they all look like this):
 ```
...Action/BaseAction.py:2368: UserWarning:
The key "_set_line_status" used to update an action will be ignored. Valid keys are {'change_line_status', 'maintenance', 'shunt', 'curtail', 'raise_alarm', 'redispatch', 'set_bus', 'raise_alert', 'change_bus', 'set_line_status', 'injection', 'set_storage', 'hazards'}
```
The initial observation (expect to see 'no_bus' / black on substation 22's storage (hexagon):
![image](https://github.com/user-attachments/assets/2e3409d6-73e0-4481-a930-a89cc33b33cc)

Any ideas what I might be missing?

**Comment by BDonnot** [comment]
Hello,

Everything appear to be on the warning here. The action is not correctly understood by grid2op. I'll address this by making sure grid2op terminates if it cannot understand the init_state action (instead of raising a warning).

I think the method "to_json" is probably not the correct one. Have you tried another one similar to this ?

**Comment by BDonnot** [comment]
Also, if you want to do such things, I would encourage you to do:

```python
import grid2op
env = grid2op.make("l2rpn_wcci_2022")

obs = env.reset(options={"time serie id":  "2050-01-03_0", "init state": {"set_bus":[(99,-1)]}})
```

I would advise against "messing with" the time series on the hard drive whenever possible

**Comment by DEUCE1957** [comment]
"I think the method "to_json" is probably not the correct one. Have you tried another one similar to this ?"
That was indeed the issue, I switched to as_serializable_dict() and now it works.

Regarding not "messing with" the time series, I wholeheartedly agree - however I will be doing so in the near-term to hack the sheddable component problem while retaining reproducibility (since I now have a pipeline to create new Grid2Op environments, including their chronics). Then I can test against that once I've implemented the shedding.

**Comment by BDonnot** [comment]
> Regarding not "messing with" the time series, I wholeheartedly agree - however I will be doing so in the near-term to hack the sheddable component problem while retaining reproducibility (since I now have a pipeline to create new Grid2Op environments, including their chronics). Then I can test against that once I've implemented the shedding.

Make total sense :-)

Feel free to close the issue if this is ok for you :-)
