### ISSUE TITLE
Rho calculation method

### ISSUE THREAD

**Issue by jacubero** [rte-france/Grid2Op#638]
Why is "rho" always calculated based on the "a_or" of the power line? Sometimes "a_ex" is greater than "a_or" and perhaps it makes sense to calculate "rho" based on the maximum value between "a_or" and "a_ex".

**Comment by BDonnot** [comment]
Hello

You are totally correct, this is a simplification. In "reality" the same powerline can have a "protection" on both its side. 

So basically there would be a "rho" on the origin side and a "rho" on the "extremity" side.

There can even be more than one "protection" for each side. For example :
-  "strong" protection that disconnect the line immediately if the current is really high
- "medium" protection that disconnect the line after say 5 or 10 minutes if the current is relatively high, but not "too high"
- "small" protection that would disconnect the line after say 15 or 20 minutes if the current is high (but not as high as the other above)

And you can have that for both sides of each powerline. Out of simplicity, we chose to simplify this and say that:
- there is a protection only on one side (a_or in our environment)
- there is no "medium" protection
- "strong" protection is called `HARD_OVERFLOW_THRESHOLD` and can be adapted in the `parameters` of the environment
- "small" protection is called `thermal_limit` and the number of steps before it disconnect the line can be parametrized in the `NB_TIMESTEP_OVERFLOW_ALLOWED` attribute of the environment `parameters`

The "thermal limits" of each released environments have been carefully fine tuned so that this does not cause too much issue.

I am not aware of a "real protections" that would look at current at both side of a powerline and computing the "max current" between a_or and a_ex. But in theory it could be another alternative for sure.

**Comment by jacubero** [comment]
Thank you for your reply, and it's clear to me now that it's a simplification you've used in the model. 

I only mentioned it because you can find situations where the difference in the value of "a_or" and "a_ex" can be really high. For example, in the first observation in the "rte_case14_realistic" environment with "test=True", in the power line between substations 4 and 5 you have the following values: a_or=99.79 A and a_ex=641.72 A with a thermal limit of 170.80 A. 

Therefore, if we calculate rho based on a_or, the power line is clearly not overloaded. However, if we calculate rho based on a_ex, the power line is very overloaded.

**Comment by BDonnot** [comment]
Hello,

Sorry for the delay I thought I answered but apparently not.

This "line" is called (in power system) a "transformer". It is a device that modifies the voltage between one of its side (in your case side "or") where the voltage is high to the same current (up to the losses) in its other side (in your example the "ex" side).

This is totally normal that the current is not the same on both its side, as the current is, roughly speeking (I do some heavy simplification here), the power transported (in MW) divided by the voltage * . So if you divide by "something large" at the `or` side you end up with less current than if you divide if by "something smaller" at the `ex` side.

There is no issue here in having a thermal limit only on one side of this device as long, as you said, as the thermal limit does not change side. And this corresponds to the reality of powergrid operation: often, for a given line or transformer, there is only one "device" that checks the current. This "device" (called `protection`) is calibrated depending on its side. If it's on side `or` or `ex` it will not have the same limit.

In your example the protection is calibrated for the `or` side and its value is 170.80. If we had decided to put it on the `ex` side, its value would not have been 170.8 but rather something like 1000 A or something. Both "`170` on `or` side" and "`1000` on `ex` side" represent the same reality, the safe "heating power"  etc.

* this is the main advantage of transporting the power over long distance using high, very high and extra high voltage: losses (proportional to `current²`) are drastically reduced (for the same transmitted power) if you divide it by a large number.

**Comment by jacubero** [comment]
Thank you for your explanation. Now I understand the logic. How can I tell if a power line is a transformer or not?

**Comment by BDonnot** [comment]
For now it's not possible directly as for grid2op powerlines and transformers are the same type of element: elements that have two sides.

To go a bit more into detail, the way to distinguish between powerlines and transformers is "backend dependant". It depends on the implementation of the backend you are using and from convention taken (by their developers) when writing these "backends".

lightsim2grid and pandapower, the two official publically available backends for now, put all the transfomers at the end of the grid2op "powerlines".

For example, for l2rpn_case14_sandbox, you have 15 real powerlines and 20 total "grid2op lines" so the last 5 "grid2op lines" are in fact transfomers.

You can do this kind of things for every grid2op environment (code snippet valid for PandaPowerBackend but result also valid for LightSimBackend):


```python
import numpy as np
import grid2op
env_name = ...
env = grid2op.make(env_name)
print(f"Number of 'real' powerlines: {env.backend._PandaPowerBackend__nb_powerline}, number of total 'grid2op powerlines' : {env.n_line}")

print(f"Indexes for 'real' powerlines {np.arange(env.backend._PandaPowerBackend__nb_powerline)}")
print(f"Indexes for 'grid2op' powerlines that are trafos {env.backend._PandaPowerBackend__nb_powerline + np.arange(env.n_line - env.backend._PandaPowerBackend__nb_powerline)}")
```

But again i'm not sure knowing this information is really important: as I tried to explained, in the reality there can be `protection` on both sides of each "powerlines" / "transformers" but today only protection at one side are implemented in grid2op. And grid2op is consistent: it check the correct side internally :-)
